name: biometricdemo
description: "Demo Biometric and Otp Authentication"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.0.4
  firebase_auth: ^5.1.4
  country_code_picker: ^3.0.0
  flutter_mobx: ^2.2.1+1
  local_auth: ^2.3.0



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

